
server:
    port: 8888
    servlet:
      encoding:
          enabled: true
          charset: utf-8
          force: true
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://132.145.110.184:3306/c_c?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
        username: nart
        password: 1234
    redis:
        host: localhost
        port: 6379
    servlet:
        multipart:
            max-request-size: 20MB
            max-file-size: 2MB

#        关闭驼峰转换，因为使用@TableField()
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
        #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:dao/*.xml

